[tool.poetry]
name = "mahou"
version = "0.0.1"
description = "Parser and Python code generator"
authors = ["RhiobeT <rhiobet@gmail.com>", "NextFire <git@yuru.moe>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/Japan7/mahou.py"

[tool.poetry.dependencies]
python = "~3.12"
pydantic = "~2"
jinja2 = "^3.1.2"
ruff = "^0.1.2"
isort = "^5.12.0"
autoflake = "^2.2.1"

[tool.poetry.group.dev.dependencies]
pyright = "^1.1.333"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py312"
