[tool.poetry]
name = "mahou"
version = "0.0.1"
description = "Parser and Python code generator"
authors = ["RhiobeT <rhiobet@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
Jinja2 = "^3.1.2"
black = "^22.10.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
balanced_wrapping = true
line_length = 99
