[tool.poetry]
name = "mahou"
version = "0.0.1"
description = "Parser and Python code generator"
authors = ["RhiobeT <rhiobet@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "~2"
jinja2 = "^3.1.2"
ruff = "^0.1.2"
isort = "^5.12.0"
autoflake = "^2.2.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
