name: CI

on:
  push:
    branches: ["master", "renovate/*"]
    tags: ["*.*.*"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') != true
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/cache@13aacd865c20de90d75de3b17ebe84f7a17d57d2 # v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml', '**/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-
      - uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5
        with:
          python-version: "3.12"
      - name: poetry install
        run: |
          pip install poetry
          poetry install
      - run: poetry run pyright
      - run: poetry run ruff check src/
        if: always()
